name: Generate and Deploy Rust Documentation

on:
  push:
    branches:
      - master

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build Documentation
        run: |
          cargo doc --no-deps --target-dir docs/docs

      - name: Commit and push the docs (optional)
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.email "lukasvrenner@icloud.com"
          git config --global user.name "GitHub Actions"
          git add docs/docs
          git commit -m "docs(api): generate API docs"
          git push origin master
